import React from 'react'

export function AppFooter() {
  return (
    <footer className="text-center p-4 bg-gray-50 border-t border-gray-200 text-xs">
      <p className="text-gray-500">
        Generated by{' '}
        <a
          className="text-primary hover:text-primary/80 transition-colors font-medium"
          href="https://github.com/solana-developers/create-solana-dapp"
          target="_blank"
          rel="noopener noreferrer"
        >
          create-solana-dapp
        </a>
      </p>
    </footer>
  )
}
